- name: Configure zoo.cfg
  template:
    src: zoo_sample.cfg.j2
    dest: "{{ INSTALLATION_DIR }}/zookeeper/conf/zoo.cfg"

- name: Configure log4j.properties
  template:
    src: log4j.properties.j2
    dest: "{{ INSTALLATION_DIR }}/zookeeper/conf/log4j.properties"

- name: Configure myid
  template:
    src: myid.j2
    dest: "{{ ZOOKEEPER_DATA_DIR }}/myid"
