---
- name: Creating host group cassandra from dynamic inventory
  hosts: localhost
  connection: local
  tags: ['info', 'install', 'start', 'stop', 'uninstall']
  vars:
    cassandra_tag_name: "tag_{{ cassandra_tag | replace('-', '_') }}"
  tasks:
    - add_host: name={{ item }} groups=cassandra
      with_items: "{{ groups[cassandra_tag_name] }}"

- name: Execute Cassandra roles
  hosts: cassandra
  user: ubuntu
  become: true
  become_method: sudo
  roles:
    - role: cassandra
