---
- name: Creating host group zookeeper from dynamic inventory
  hosts: localhost
  connection: local
  tags: ['info', 'install', 'start', 'stop', 'uninstall']
  tasks:
    - add_host: name={{ item }} groups=zookeeper
      with_items: "{{ groups[zookeeper_tag] }}"

- name: Execute Zookeeper roles
  hosts: zookeeper
  user: ubuntu
  become: true
  become_method: sudo
  roles:
    - role: zookeeper
