---
- name: Get stopped C2 instances for the given tag
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ tag_key_vals.Name }}"
      instance-state-name: stopped
  register: ec2_info

- name: Start EC2 instances specified by the given tag
  ec2:
    state: running
    region: "{{ region }}"
    wait: True
    instance_ids: "{{ item.id }}"
  with_items: "{{ ec2_info.instances }}"
